# Generated by Django 5.2.6 on 2025-10-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='pos.shop'),
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pos.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pos.shop'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pos.shop'),
        ),
        migrations.AddField(
            model_name='wasteproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_products', to='pos.shop'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('HR', 'HR'), ('CASHIER', 'Cashier')], default='SUPER_ADMIN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('shop', 'name')},
        ),
    ]
