# Generated by Django 5.2.6 on 2025-10-01 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_orderitem_color_name_orderitem_size_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='The positive or negative adjustment amount.', max_digits=12)),
                ('description', models.TextField(help_text='Reason for the adjustment (e.g., inventory write-off, bank error correction).')),
                ('adjustment_type', models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss/Write-off'), ('CORRECTION', 'Correction')], default='CORRECTION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pos.shop')),
                ('user', models.ForeignKey(blank=True, help_text='User who recorded the adjustment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Adjustment',
                'verbose_name_plural': 'Financial Adjustments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date the expense was incurred or recorded.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the expense.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(help_text='Detailed description of the expense.')),
                ('category', models.CharField(choices=[('RENT', 'Rent/Lease'), ('UTILITY', 'Utilities (Electric, Water)'), ('SALARY', 'Salaries & Wages'), ('MARKETING', 'Marketing & Advertising'), ('SUPPLIES', 'Office Supplies'), ('OTHER', 'Other')], default='OTHER', help_text='Category of the expense for reporting.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.shop')),
                ('user', models.ForeignKey(blank=True, help_text='User who recorded the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operating Expense',
                'verbose_name_plural': 'Operating Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
