# Generated by Django 5.2.6 on 2025-10-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_orderitem_color_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='waste_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wasteproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to='pos.productvariant'),
        ),
    ]
