# Generated by Django 5.2.6 on 2025-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_employee_attendance_payroll_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
