# Generated by Django 5.2.6 on 2025-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_payroll_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('On Time', 'On Time'), ('Absent', 'Absent'), ('Paid Leave', 'Paid Leave'), ('Unpaid Leave', 'Unpaid Leave')], default='Present', max_length=20),
        ),
    ]
