# Generated by Django 5.2.6 on 2025-10-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_holiday_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='rating',
            field=models.CharField(choices=[('Best', 'Best'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor'), ('N/A', 'Not Applicable')], default='N/A', max_length=20),
        ),
    ]
