# Generated by Django 5.2.6 on 2025-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_performance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absent_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('HR', 'HR'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=20),
        ),
    ]
