# Generated by Django 5.2.6 on 2025-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_payroll_absent_deduction_amount_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN, UPC, or custom product code', max_length=50, null=True, unique=True),
        ),
    ]
