# Generated by Django 5.2.6 on 2025-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_order_paid_amount_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debttobepaid',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='debttobepaid',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
