# Generated by Django 5.2.6 on 2025-10-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_debttobepaid_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debttopay',
            name='amount',
        ),
        migrations.AddField(
            model_name='debttopay',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='debttopay',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='pos.product'),
        ),
        migrations.AddField(
            model_name='debttopay',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='debttopay',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
