# Generated by Django 5.2.6 on 2025-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_remove_debttopay_amount_debttopay_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_supplier_per_shop'),
        ),
    ]
