# Generated by Django 5.2.6 on 2025-10-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_per_shop',
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('shop', 'name')},
        ),
    ]
