# Generated by Django 5.2.7 on 2025-10-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
