# Generated by Django 5.2.7 on 2025-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
