# Generated by Django 5.2.7 on 2025-11-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_shop_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='linked_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_variants', to='pos.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
