# Generated by Django 5.2.7 on 2025-11-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_productvariant_is_pack_productvariant_linked_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='linked_variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='linked_single_variant',
            field=models.ForeignKey(blank=True, help_text='If this is a pack, link to the single-item variant it represents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_packs', to='pos.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_pack',
            field=models.BooleanField(default=False, help_text='If True, this variant is a package (e.g., 12-pack)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, help_text='How many single items are in one pack'),
        ),
    ]
