# Generated by Django 5.2.7 on 2025-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_remove_productvariant_linked_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='pack_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Different selling price when sold as a pack', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='single_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Different selling price when sold as a single item', max_digits=10, null=True),
        ),
    ]
