# Generated by Django 5.2.7 on 2025-11-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_productvariant_pack_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size', 'is_pack')},
        ),
    ]
